### ISSUE TITLE
Sounds not registering when using a json file manifest

### ISSUE THREAD

**Issue by fatlinesofcode** [CreateJS/PreloadJS#117] opened 2015-01-30 04:43 UTC
Hi,
using 0.6.0 of Preload + SoundJs sounds always come back as playFailed when loaded through a json manifest in this format:
```
{
"manifest":[{"src" : "./assets/audio/02_music_raid.mp3", "id" : "bg-music"}] 
}
```

Loading the mp3 direct works fine
```
queue = new createjs.LoadQueue();
            scope.queue.installPlugin(createjs.Sound);
            queue.setMaxConnections(10); // Allow 10 concurrent loads
            queue.on("fileload", onPreloadFile, this);
            queue.on("progress", onLoadProgress, this);

            queue.on("complete", onPreloadComplete, this);
            queue.loadFile({src:"./assets/audio/02_music_raid.mp3", id:'bg-music'});
            queue.loadManifest('sitedata.json');

 var onPreloadFile = function(evt) {

            if(evt.item.type == "sound"){
                console.log("32","onPreloadFile","onPreloadFile", evt.item, evt.item.id);
                var s = createjs.Sound.play(evt.item.id);
                console.log("37","onPreloadFile","onPreloadFile", s);
            }

        }
```

Here is the log output of the playFailed
![screen-capture-15](https://cloud.githubusercontent.com/assets/505776/5971314/99e44918-a896-11e4-9ec3-2ea83f75b751.jpg)

Note how *src* isn't correct.

**Comment by OJayRobinson** [comment] 2015-04-21 16:02
This has been resolved in SoundJS-Next and PreloadJS-Next, available on github.

This was caused by plugins from the top loader not being passed on to sub-loaders

**Closed** 2015-04-21 16:03 UTC
Labels: bug
