### ISSUE TITLE
_loadedResults resource leak when using TagLoader and relative paths

### ISSUE THREAD

**Issue by michamil** [CreateJS/PreloadJS#87] opened 2014-06-04 20:46 UTC
My use case is where I load sound files using the TagLoader (HTMLAudioPlugin), and use relative paths to the files.

Items are removed from _loadItemsBySrc in remove() (at line 2535 in preloadjs-NEXT.combined.js) using the src property of the object "r" which is returned from LoadQueue.getResult().  That object ("r") is (in my use-case) an object which was stored in _loadedResults, and (if one is using a TagLoader) is actually the HTML tag.  The src property of HTML audio tags is the full path, http://etc.  However, the items in _loadItemsBySrc get their key from the src property of objects handed in to loadManifest(), which can be relative paths.  An example for me would be { id: "btnClick", src: "assets/audio/sfx_click.mp3"}.  When the LoadQueue tries to delete _loadItemsBySrc["http://some.server.com/somesubpath/assets/audio/sfx_click.mp3"] it fails, and the items in _loadItemsBySrc persist.

Because those items have refs to the audio tags, this causes a leak which is particularly troublesome for IE9 - causing it to eventually fail to load sounds.

**Comment by wdamien** [comment] 2015-04-02 16:46
I cannot reproduce this with the latest NEXT build. Closing for now, feel free to re-open if the issue persists.

**Closed by wdamien** 2015-04-02 16:46 UTC
Labels: bug
