### ISSUE TITLE
VideoLoader

### ISSUE THREAD

**Issue by fatlinesofcode** [CreateJS/PreloadJS#115] opened 2015-01-26 21:51 UTC
Is there any examples on how to preload video with 0.6.0? I've tried several methods and am having no luck. The files do load in the loadQueue but I can't access the result.

Using 
```
document.body.appendChild(event.result);
```
Does insert a video tag but its not playable, the source seems to be encoded or corrupt when I look at the html in the inspector. 
![screen-capture-12](https://cloud.githubusercontent.com/assets/505776/5909073/365b4c94-a601-11e4-9322-31f6649ca9eb.jpg)

I've also tried creating my own video object and setting the source to the preloaded data e.g.

```
myvideo.src = queue.getResult('video-story').src;
```

or the using raw result
```
var video = document.createElement('video'), source = document.createElement('source');
video.controls = "controls";
video.autoplay = "autoplay";
source.src = event.rawResult;
source.type = "video/mp4";
video.appendChild(source);
document.body.appendChild(video)
```

this also fails.

**Comment by fatlinesofcode** [comment] 2015-01-26 22:25
Here's an example, http://plnkr.co/edit/5zNS0FLs0cnJalrusWvE?p=info

**Comment by fatlinesofcode** [comment] 2015-01-30 09:25
Additional switching xhr to false does load the correct video tag but it does not preload the data e.g.

http://plnkr.co/edit/XOChQk5rEp0J0LjpOOaf?p=preview

**Comment by chrislo2401** [comment] 2015-08-06 05:47
I know this is an old issue but I've come across it as I have the same problem. The injected video tag looks the same as the example above, and it doesn't play at all.

Is there a working example I could follow?

Thanks.

**Comment by wdamien** [comment] 2015-08-06 15:08
No examples, but we have a couple tests you can reference: https://github.com/CreateJS/PreloadJS/blob/master/tests/spec/LoadQueueSpec.js#L85

**Comment by booc0mtaco** [comment] 2015-08-27 23:00
I'm also having problems with this. I very nearly switched to another library because this page (<http://www.createjs.com/docs/preloadjs/classes/LoadQueue.html>) doesn't mention video.

I tried the examples above, and neither seems to work anymore (tried in Safari and Chrome). As others have stated, the tag does appear on the page, but never loads or works out of the box. An example of this would be very helpful indeed.

**Comment by netpalantir** [comment] 2015-10-30 17:39
(Rumbling rants removed :) ).

I skipped the VIDEO loader altogether, and I jumped straight to the BINARY loader. From there I got an objectUrl which I plugged into the video source.

I suspect that returning a `<video>` element that has raw binary data inside its `src` attribute is not correct. As far as I know, the src attribute for media files is supposed to be a valid URL, and binary data are not. This is what the libary does at the moment.

Here is a working fiddle rewriting the previous example. Sorry if it is messy.
https://jsfiddle.net/uukyt2qf/

**Comment by wdamien** [comment] 2015-10-30 17:52
This has been fixed in the latest NEXT version, see #160 for details.

**Closed by wdamien** 2015-10-30 17:52 UTC
Labels: question

**Comment by atari83** [comment] 2015-11-06 21:21
Hello @wdamien, 
just wanted know if the problem is resolved. I see you mentioned it is already patched for NEXT version. Well I've tried with 0.6.1 + NEXT versions but I still have the problem with loading video ...

**Comment by lannymcnie** [comment] 2015-11-06 21:24
The NEXT version is available in GitHub only, and is how we refer to the compiled version of the latest changes in the master branch. Once it is "tagged", it will become available on the CreateJS CDN. We expect version 0.6.2 to be released at the beginning of December. For now, you can find the latest builds here: https://github.com/CreateJS/PreloadJS/tree/master/lib

**Comment by atari83** [comment] 2015-11-06 21:47
Thank you @lannymcnie :)
My bad !! just two days ago I used bower to get some libraries (createjs included). actually didn't check the resolved date for this issue :D

I had only 2 hours to for upload new pages on the production system ( +1 hr is remaining ;) ).
Thank you guys!
