### ISSUE TITLE
Jumping stage (tag-based loading)

### ISSUE THREAD

**Issue by LicVit** [CreateJS/PreloadJS#163] opened 2015-11-01 18:49 UTC
When loading images with width or height bigger than appropriate dimension of the screen - stage is jumping. It's like stage width(or height) temporary increases, and then the stage is trying to fit the screen dimensions). Sometimes it makes the stage stuck at this wrong size after preloading.

It happen ONLY when preferXHR is false
(var preloader  = new createjs.LoadQueue(false); )

Test device: 
Iphone 6 Plus, IOS 8.3, Safari & Chrome, screen1920x1080

Test images:
Semi-transparent png images. Only  big images (2212x578) caused the problems

 PreloadJS versions:
All versions >= 6.0

**Comment by lannymcnie** [comment] 2015-11-01 23:36
Images are added to the DOM when preloading using tags -- but they should not be visible. I wonder if this is the cause. We will check it out.

**Comment by lannymcnie** [comment] 2015-11-17 17:04
This looks fixed in iOS9.

**Comment by lannymcnie** [comment] 2015-11-17 23:10
We have pushed a fix for this to GitHub. Thanks for the report!

**Comment by wdamien** [comment] 2015-11-20 21:36
Using ```style.display=none``` breaks SVG tag loading.  Revered back to ```style.visibility=hidden``` for now. We will have to selectively choose what style to use when adding tags to the dom.

**Comment by trevordunn** [comment] 2016-01-13 22:55
One idea might be to add all tags to a div that has "width:0;height:0;overflow:hidden;" on it. That should allow you to keep using "visibility: hidden;" and still allow all media elements to load.

**Comment by phenmaleat** [comment] 2016-03-30 02:09
I think my page has the same problems with you. 
When loading image resources, IMG tags will be created and append to Dom body tag, but those IMG tags have css property "visibility: hidden;", not "display:none", or not "width:0;height:0;" → it breaks my page in a second, scroll bar appears in a moment.

**Comment by pkupiec** [comment] 2016-10-11 17:18
Hot-fix that works for img tags and version 0.6.2 :
`body > img:last-child[style="visibility: hidden;"]{
      display: none;
}`

**Comment by paponius** [comment] 2016-11-18 07:27
> Using style.display=none breaks SVG tag loading.

modified @pkupiec hot-fix to avoid SVG files:
`body > img:last-child[style="visibility: hidden;"]:not([src$=".svg"]){ display: none; }`

We don't have svg in our project to test this, but if they are in a form of a svg file:
`<img src="pichuhu.svg" style="visibility: hidden;">`
this above fix should work.

watch out for case, pichuhu.SVG will get `display: none`

**Comment by lannymcnie** [comment] 2016-11-30 16:54
Considering an approach where we create a document-level DIV that is `visiblity:none; position:absolute;`, and any content we need in the DOM to load can be placed in that DIV. This prevents scroll jumping entirely. 

We wanted to avoid affecting loaded items too much by adding a bunch of properties, since you can pass in existing IMG tags to the preloader, and we don't want to affect their initial state incorrectly.

I have tested this approach, and it works great, but leaves an element in the root. Open to thoughts.

**Comment by francescom** [comment] 2017-08-31 20:36
Hello, I am affected by this problem on createjs-2015.11.26, has this been solved in later releases?
I would modify the source if I knew where, creating a div and later removing it seems the best solution.
Thanks.

**Comment by lannymcnie** [comment] 2017-08-31 23:55
Yes, it is resolved in the NEXT version. You can see the change with these commits:

https://github.com/CreateJS/PreloadJS/commit/5fee059a3ae7ecaadc8ce73c55f0db3db0d460c4
https://github.com/CreateJS/PreloadJS/commit/8c4af7e381ccaf9e112b67d549333eefe1d263b7

The solution was to put loading content in a container that doesn't affect layout, rather than in the document root.

Cheers.

**Closed** 2017-08-31 23:55 UTC
Labels: bug, NextRelease, verified
